# Generated by Django 4.1.5 on 2023-01-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_main', '0002_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
