# Generated by Django 4.1.5 on 2023-01-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_main', '0002_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='favorites',
        ),
        migrations.AddField(
            model_name='favorites',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
    ]
