# Generated by Django 4.1.5 on 2023-01-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_main', '0003_cart_price_alter_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='in_cart',
        ),
    ]
