# Generated by Django 4.1.5 on 2023-01-27 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_main', '0004_alter_stuffs_category_alter_stuffs_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuffs',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stuffs', to='marketplace_main.category'),
        ),
    ]
