# Generated by Django 4.1.5 on 2023-01-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_main', '0004_alter_favorites_user'),
        ('marketplace_main', '0004_likes'),
    ]

    operations = [
    ]
